name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  check-terraform-module:
    name: Check Terraform Module
    uses: canonical/observability/.github/workflows/terraform.yaml@main
    secrets: inherit
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@main
    secrets: inherit
